# Generated by Django 4.2.7 on 2023-11-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='viewed',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
